{% raw %}
scrape_configs:
  - job_name: alertmanager
    static_configs:
      - targets:
{% for host in groups['prometheus-alertmanager'] %}
        - "{{ 'api' | kolla_address(host) | put_address_in_context('url') }}:{{ prometheus_alertmanager_port }}"
{% endfor %}
{% endraw %}
